name: python-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pylint
    - name: make all
      run: |
        pylint ./3_Implementation/src/DeleteHospital.py 
        pylint ./3_Implementation/src/HospitalDetailsAdd.py
        pylint ./3_Implementation/src/HospitalDisplayPatient.py
        pylint ./3_Implementation/src/Hospital_payment_portal.py
        pylint ./3_Implementation/src/VaccineRegister.py
        pylint ./3_Implementation/src/book_appointment.py
        pylint ./3_Implementation/src/docregister.py
        pylint ./3_Implementation/src
